events {}
http {
    upstream backend {
        server node1:8081;
        server node2:8082;
        server node3:8083;
        server node4:8084;
        server node5:8085;
    }
    server {
        listen 8080;
        location / {
            proxy_pass http://backend;
        }
    }
}
