spring.application.name=DS_project

server.port=8081
node.id=node-${server.port}

nodes=http://localhost:8081,http://localhost:8082,http://localhost:8083
node.url=http://localhost:${server.port}
zookeeper.url=localhost:2181
